title:              Day_learner Blog
email:              dswcrispr@gmail.com
description:        A Blog for recording daily learning 
author:             dswcrispr
baseurl:            ""
url:                "https://dswcrispr.github.io"

# Social Profiles
twitter_username:   None
github_username:    dswcrispr
facebook_username:  None
instagram_username: None 
linkedin_username: None

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
